### PR TITLE
CMake build for Mathic

### PR DESCRIPTION
**Pull request by mahrud**
This PR improves the CMakeLists.txt file in the master branch to be a full replacement for the configure.ac script. This is how you would "configure", build, test, and install using CMake:
```
cmake -GNinja -B tmp -S . -DCMAKE_INSTALL_PREFIX=/usr
cmake --build tmp
cmake --build tmp --target test
cmake --install tmp
```
The `-GNinja` option instructs CMake to produce `build.ninja` files instead of `Makefiles` to go with the Ninja build system, which is faster and more efficient than `make`.

Note that Memtailor would need to be installed in the `CMAKE_INSTALL_PREFIX` first.

### CODE REVIEW

**Comment by mahrud** [comment]
PS: the PR also fixes incorrect permissions on source files.

**Comment by mikestillman** [comment]
> This PR improves the CMakeLists.txt file in the master branch to be a full replacement for the configure.ac script. This is how you would "configure", build, test, and install using CMake:
> 
> ```
> cmake -GNinja -B tmp -S . -DCMAKE_INSTALL_PREFIX=/usr
> cmake --build tmp
> cmake --build tmp --target test
> cmake --install tmp
> ```
> 
> The `-GNinja` option instructs CMake to produce `build.ninja` files instead of `Makefiles` to go with the Ninja build system, which is faster and more efficient than `make`.
> 
> Note that Memtailor would need to be installed in the `CMAKE_INSTALL_PREFIX` first.

@mahrud  How is cmake finding memtailor?  I am not putting it in /usr/local (I change the install prefix to be e.g. ~/tmp/installed), so it needs to be told how to find it.  Perhaps we should have a readme file in here saying how to build with cmake?  (Same with memtailor, actually).  (I know that such a file for how to build using `configure` is missing, and we should also have that.!)

**Comment by DanGrayson** [comment]
Mike, why put memtailor and friends anywhere?  Just develop them as submodules of M2, in place.

**Comment by mahrud** [comment]
> @mahrud How is cmake finding memtailor? I am not putting it in /usr/local (I change the install prefix to be e.g. ~/tmp/installed), so it needs to be tolhttps://github.com/Macaulay2/mathic/pull/5/files#diff-482758854e7d81bffe2e038a178605deR13-R19d how tohttps://github.com/Macaulay2/mathic/pull/5/files#diff-482758854e7d81bffe2e038a178605deR13-R19 find it. Perhaps we should have a readme file in here saying how to build with cmake? (Same with memtailor, actually). (I know that such a file for how to build using `configure` is missing, and we should also have that.!)

That's exactly it, if you add `-DCMAKE_INSTALL_PREFIX=~/tmp/installed` to all three parts (memtailor, mathic, mathicgb) and install them in order, they can find each other. The logic is in `cmake/FindMemtailor.cmake` here:
https://github.com/Macaulay2/mathic/pull/5/files#diff-482758854e7d81bffe2e038a178605deR13-R19

**Comment by mikestillman** [comment]
I checked that the cmake build works, and as it seems no other files are affected (other than perhaps changing permissions) the configure build should work fine with it.  I'm accepting this pull request.

**Comment by DanGrayson** [comment]
We won't advance the pointer from M2 to mathic until after complete testing of the new value in overnight testing on the development branch, so if there were a problem with the configure build, we would catch it at that point.

**Pull request merged**
